# Generated by Django 5.1.7 on 2025-03-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("pin", models.TextField()),
                ("firstname", models.CharField(max_length=250)),
                ("lastname", models.CharField(max_length=250)),
                ("middlename", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("balance", models.FloatField(default=0.0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("savings", "Savings"), ("current", "Current")],
                        max_length=10,
                    ),
                ),
                ("interest_rate", models.FloatField(default=0.03)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                            ("interest_credit", "Interest Credit"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.FloatField()),
                ("balance_after", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
            ],
        ),
    ]
