# Generated by Django 5.1.7 on 2025-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_account_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="middlename",
        ),
        migrations.RemoveField(
            model_name="account",
            name="pin",
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(auto_created=True, max_length=50, unique=True),
        ),
    ]
